version: '3'

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./src:/opt/app/src
  environment:
    - LOG_DIR="/var/log"
